---
- !ruby/object:Order
  book: &1 !ruby/object:Book
    title: Black man
    author: &2 !ruby/object:Author
      name: Sergey Yesenin
      biography: Happyness
  reader: !ruby/object:Reader
    name: Mat
    email: email@email
    city: Dnipro
    street: Street
    house: 5
  date: 2018-11-20 13:16:43.290069703 +02:00
- !ruby/object:Order
  book: *1
  reader: &3 !ruby/object:Reader
    name: Sat
    email: mail@mail
    city: Kiev
    street: Street
    house: 7
  date: 2018-11-20 13:16:43.290074667 +02:00
- !ruby/object:Order
  book: *1
  reader: &4 !ruby/object:Reader
    name: Nat
    email: gmail@gmail
    city: Lviv
    street: Street
    house: 8
  date: 2018-11-20 13:16:43.290076983 +02:00
- !ruby/object:Order
  book: *1
  reader: &5 !ruby/object:Reader
    name: Bat
    email: freemail@freemail
    city: city:man
    street: Street
    house: 10
  date: 2018-11-20 13:16:43.290078798 +02:00
- !ruby/object:Order
  book: !ruby/object:Book
    title: About love
    author: *2
  reader: *3
  date: 2018-11-20 13:16:43.290080698 +02:00
- !ruby/object:Order
  book: !ruby/object:Book
    title: The Murder of Roger Ackroyd
    author: !ruby/object:Author
      name: Agatha Christie
      biography: Desert
  reader: *4
  date: 2018-11-20 13:16:43.290082355 +02:00
- !ruby/object:Order
  book: !ruby/object:Book
    title: Heart of a Dog
    author: !ruby/object:Author
      name: Michael Bulgakov
      biography: Love
  reader: *5
  date: 2018-11-20 13:16:43.290084027 +02:00
- !ruby/object:Order
  book: !ruby/object:Book
    title: Eugene Onegin
    author: !ruby/object:Author
      name: Ivan Krilov
      biography: Freedom
  reader: !ruby/object:Reader
    name: Kat
    email: freemail@freemail
    city: Oslo
    street: Street
    house: 11
  date: 2018-11-20 13:16:43.290085696 +02:00
